### ISSUE TITLE
xinput1_4 missing error

### ISSUE THREAD

**Issue by coastercrab** [xan1242/NFSU-XtendedInput#14] opened 2022-12-05 22:30 UTC
If I rename 1_3 to 1_4 and put in the game folder it loads, but I still have the same "infinite scrolling up" bug as before, so I don't think it works.

**Comment by xan1242** [comment] 2022-12-05 22:36
The "scrolling bug" is probably related to this: https://github.com/xan1242/NFS-XtendedInput/issues/44 

Null VKey is always high for whatever reason.

As for xinput missing errors, all of that is caused by the configuration of the OS. No intervention was necessary on my end with either Win10 or 11, or even Wine/Proton under Linux.

The latest release is linked against XINPUT1_4.dll so it'll always expect it to be there.

**Comment by coastercrab** [comment] 2022-12-06 01:02
Yeah. Looks like I'm out of luck since win7 doesn't have xinput1_4.dll :(
It does share XInput 9.1.0 that *8+ all have for backwards compatibility reasons, and of course 1.3.

I'm going to download the win8 sdk and see if that gives me 1.4.
Edit; that didn't give me it, but I found one in the files of the game "Control". That could just be a dummy, because I still have the scrolling bug and none of the gui buttons were changed.

**Comment by xan1242** [comment] 2022-12-06 11:58
If you're building it yourself already, just compile it. It'll automatically use the correct library.

On a second note, I'll be making Win7 builds available soon.

**Comment by coastercrab** [comment] 2023-01-29 03:33
I'm afraid I'm to stupid to build myself - I tried and I don't even know which file to open in VScode. I would have thought opening the vsproj file would do something, but it just shows me the text inside this file instead of actually opening a project. I tried the remote repository extension thing (is that even the right thing to do if it's not mine?), and it just said no.

I would really appreciate a win7 build, unless you think I'm anywhere near close to getting your code to build lol

**Comment by xan1242** [comment] 2023-01-29 07:46
I'll see to it as soon as I get back to working on NFS stuff (been busy this past month).

As for building - you do not use VS Code. You must use a version of the regular Visual Studio (VS Community for example). You'd just open the solution file (.sln) and then build it. 

You may only have to reconfigure the build tools to use another version (like v140, which is 2015) and it should work.

**Comment by xan1242** [comment] 2023-01-29 19:43
@coastercrab The Windows 7 builds have been created and released in 2.7.

https://github.com/xan1242/NFSU-XtendedInput/releases/tag/2.7

Enjoy!

**Closed as completed by xan1242** 2023-01-29 19:43 UTC
